name = "whatthesub-api"
main = "src/index.js"
compatibility_date = "2024-09-23"
account_id = "82fcff5fb1a0de92c409f86edd495985"
workers_dev = true

[[kv_namespaces]]
binding = "PUZZLES"
id = "010130a100d74b3f9e43f6147ed22444"

[[d1_databases]]
binding = "DB"
database_name = "whatthesub-db"
database_id = "819c4eb8-d1a2-4b61-a31a-e53c80789c9d"
